namespace: kafka-sample
clusterName: kafka

#Brokers
brokers:
  replicas: 1
  version: 3.7.0
  volumes:
  - id: 0
    type: persistent-claim
    size: 5Gi
    deleteClaim: false
    class: local-storage
  listeners:
  - name: plain
    port: 9092
    type: internal
    tls: false
  - name: tls
    port: 9093
    type: internal
    tls: true
  - name: external
    port: 9094
    type: nodeport
    tls: false
  config:
    offsets.topic.replication.factor: 1
    transaction.state.log.replication.factor: 1
    transaction.state.log.min.isr: 1
    default.replication.factor: 1
    min.insync.replicas: 1
    inter.broker.protocol.version: "3.5"
  storage:
    type: jbod
    volumes:
    - id: 0
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
      class: local-storage

#zookeeper
zookeeper:
  replicas: 1
  storageType: persistent-claim
  storageSize: 5Gi
  storageDeleteClaim: false
  storageClass: local-storage